# Use the Official Bun image
FROM oven/bun:1.1.13 as base

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and bun.lockb
COPY package.json bun.lockb ./

# Install dependencies
RUN bun install

# Copy the rest of the application code
COPY . .

# Expose the port
EXPOSE 3000

# Run the development server
CMD ["bun", "dev"]