version: '3.9'

services:
  mysql:
    container_name: media_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    volumes:
      - db_store:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - media

  redis:
    container_name: media_cache
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - cache_store:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - media

volumes:
  db_store:
  cache_store:

networks:
  media: